# Generated by Django 4.1.5 on 2023-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time', models.IntegerField(default=0)),
                ('off_time', models.IntegerField(default=0)),
            ],
        ),
    ]
